### ISSUE TITLE
Mixed content error

### ISSUE THREAD

**Issue by andrewyates** [lintool/scholar-scraper#7]
Current Chrome (85.0.4183.83 on Linux) fails to populate the list with this error message:
>  Mixed Content: The page at 'https://lintool.github.io/scholar-scraper/index.html' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

**Comment by lintool** [comment]
Closed by commit 70ed2d491ab6bbce1731721e0a5315d466c75511
